### ISSUE TITLE
Why so complicated?

### ISSUE THREAD

**Issue by probonopd** [juanmcloaiza/AppImageExample#1]
https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci has an example that should work in most cases...

**Comment by juanmcloaiza** [comment]
Hey, thanks for getting in touch! In this "AppImageExample" repository I wanted to do some AppImage "hello world" that does not need anything else (e.g. travis ci)  than the bare essentials: linux-deploy-qt, but, indeed, I followed your example in the repo https://github.com/juanmcloaiza/Steca/tree/AppImage

I also tried your uploadtool somewhere else: https://github.com/juanmcloaiza/BornAgain/tree/uploaddebpack

AppImage and your uploadtool: really cool software!

**Comment by probonopd** [comment]
Thanks for your kudos and for the explanation. Looking forward to your AppImages :+1:
